services:

  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm start"
    networks:
      - noginx-network
    volumes:
      - ./node:/usr/src/app
      # - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    # image: mysql:8.0.33
    build:
      context: ./data
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - noginx-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - noginx-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  noginx-network:
    driver: bridge